#!/bin/bash

#########################################################
### Bash script to download files from a remote server. #
### Last modified: 02/2021			      	#
### Author: Mathias Roesler		      	      	#
### Contact: mathias.roesler@univ-reims.fr    	      	#
#########################################################


source server_functions
define_const


function print_usage() {
	# Prints function usage.
	#
	# Arguments:
	# Return:
	#
	printf "Usage: $NAME [-hr] [-p number] server file ... destination\n"
	printf "Copy file from remote server to destination or "
	printf "multiple files from remote server to destination "
	printf "directory using scp.\n\n"
	printf "Options:\n"
	printf " -h, print help.\n"
	printf " -r, copy directories recursively.\n"
	printf " -p number, specify port number.\n"
	available_servers

return 0
}


RECURSIVE=false
PORT=false
port_number=22

# Parse options
while getopts ":rhp:s:" opt; do
	case $opt in
		r) 
			RECURSIVE='true' 
			;;
		h) 
			print_usage
			exit 
			;;
		p)
			port_number=${OPTARG}
			PORT=true
		       	;;
		?)
			error_handler "invalid option."
			;;
	esac
done

argument_nb_check $# 3

# Shift to first argument after options
shift $(($OPTIND - 1))

set_connection_params $1; shift

ARGS="$@"
destination=${@: -1}
files=${ARGS%${destination}}

if [[ $RECURSIVE == 'true' ]]; then
	print_info
	scp -rP $port_number $options $server:$files $destination

else
	print_info
 	scp -P $port_number $options $server:$files $destination
fi

