#!/bin/bash

#########################################################
### Bash script to download files from a remote server. #
### Last modified: 02/2021			      	#
### Author: Mathias Roesler		      	      	#
### Contact: mathias.roesler@univ-reims.fr    	      	#
#########################################################


source server_functions
define_const


function print_usage() {
	# Prints function usage.
	#
	# Arguments:
	# Return:
	#
	printf "Usage: $NAME [-hlLr] [-adm server] [-p port] [-o options] server file ... "
	printf "destination\n"
	printf "Copy file from remote server to destination or "
	printf "multiple files from remote server to destination "
	printf "directory using scp.\n\n"
	print_options true

return 0
}


RECURSIVE=false
PORT=false
OPTION=false

# Parse options
while getopts ":hlLra:d:m:p:o:" opt; do
	case $opt in
		h) 
			print_usage
			exit 0
			;;
		l)
			print_available_servers "help"
			exit 0
			;;
		L)
			print_available_servers "long" "help"
			exit 0
			;;
		r) 
			RECURSIVE='true' 
			;;
		a)
			server=${OPTARG}
			ADD=true
			;;
		d)
			server=${OPTARG}
			DELETE=true
			;;
		m)
			server=${OPTARG}
			MODIFY=true
			;;
		p)
			port_number=${OPTARG}
			PORT=true
		       	;;
		o)
			options=${OPTARG}
			OPTION=true
			;;
		?)
			error_handler "invalid option."
			;;
	esac
done

if [[ $ADD == true ]]; then
	add_server 
	exit 0
fi

if [[ $DELETE == true ]]; then
	delete_server
	exit 0
fi

if [[ $MODIFY == true ]]; then
	modify_server
	exit 0
fi

argument_nb_check $# 3

# Shift to first argument after options
shift $(($OPTIND - 1))

set_connection_params $1; shift

ARGS="$@"
destination=${@: -1}
files=${ARGS%${destination}}

if [[ $RECURSIVE == 'true' ]]; then
	print_info
	scp -rP $port_number $options $server:$files $destination

else
	print_info
 	scp -P $port_number $options $server:$files $destination
fi

