#!/bin/bash

source server_functions

function print_usage() {
	# Prints function usage.
	#
	# Arguments:
	# Return:
	#
	printf "Usage: $NAME [-h] [-p number] server \n" 
	printf "Connects to a remote server using ssh. There are $NB_SERVERS"
	printf " available servers:\n"
	available_servers
	printf "Options:\n"
	printf " -h, print help.\n"
	printf " -p number, specify port number.\n"

return 0
}


PORT=false
port_number=22

# Parse options
while getopts ":hp:" opt; do
	case $opt in
		h) 
			print_usage
			exit 
			;;
		p)
			port_number="${OPTARG}"
			PORT=true
		       	;;

		?)
			echo "$NAME: invalid option."
			echo "Try '$NAME -h' for help."
			exit
			;;
	esac
done

# Shift to first argument after options.
shift $(($OPTIND - 1))

if [[ $# -lt 1 ]]; then
	echo "$NAME: not enough arguments."
	echo "Try '$NAME -h' for help."
	exit
fi


set_connection_params $1

print_info
ssh -p $port_number $options $server 
