#!/bin/bash

#########################################################
### Bash script to upload files to remote server. 	#
### Last modified: 02/2021		      		#
### Author: Mathias Roesler		      		#
### Contact: mathias.roesler@univ-reims.fr    		#
#########################################################


source server_functions
define_const


function print_usage() {
	# Prints function usage.
	#
	# Arguments:
	# Return:
	#
	printf "Usage: $NAME [-hlLr] [-adm server] [-p port] [-o options] [-c comment] server file ... "
	printf "destination\n"
	printf "Copy file to remote server destination or multiple files "
	printf "to remote server destination using scp.\n\n"
	print_options true

return 0
}


# Parse options
while getopts $ARGUMENTS opt; do
	parse_args $opt
done

if [[ $ADD == true ]]; then
	add_server 
	exit 0
fi

if [[ $DELETE == true ]]; then
	delete_server
	exit 0
fi

if [[ $MODIFY == true ]]; then
	modify_server
	exit 0
fi

# Shift to first argument after options.
shift $(($OPTIND - 1))

argument_nb_check $# 2

set_connection_params $1; shift

ARGS="$@"

if [[ $# -gt 1 ]]; then
	destination=${@: -1}
	files=${ARGS%${destination}}

else
	# If only the source was given.
	destination=""
	files=$ARGS
fi

if [[ $RECURSIVE == 'true' ]]; then
	print_info
	scp -rP $port_number $files $options $server:$destination

else
	print_info
	scp -P $port_number $files $options $server:$destination
fi

