#!/bin/bash

#########################################################
### Bash script to upload files to remote server. 	#
### Last modified: 02/2021		      		#
### Author: Mathias Roesler		      		#
### Contact: mathias.roesler@univ-reims.fr    		#
#########################################################


source server_functions
define_const


function print_usage() {
	# Prints function usage.
	#
	# Arguments:
	# Return:
	#
	printf "Usage: $NAME [-hlr] [-p number] server file ... destination\n"
	printf "Copy file to remote server destination or multiple files "
	printf "to remote server destination using scp.\n\n"
	print_options true

return 0
}


RECURSIVE=false
PORT=false
port_number=22

# Parse options
while getopts ":hlrp:" opt; do
	case $opt in
		h) 
			print_usage
			exit 0
			;;
		l)
			available_servers
			exit 0
			;;
		r) 
			RECURSIVE='true' 
			;;
		p)
			port_number="${OPTARG}"
			PORT=true
		       	;;

		?)
			error_handler "invalid option."
			;;
	esac
done


# Shift to first argument after options.
shift $(($OPTIND - 1))

argument_nb_check $# 3

set_connection_params $1; shift

ARGS="$@"
destination=${@: -1}
files=${ARGS%${destination}}

if [[ $RECURSIVE == 'true' ]]; then
	print_info
	scp -rP $port_number $files $options $server:$destination

else
	print_info
	scp -P $port_number $files $options $server:$destination
fi

